port = 3002
socketPort = 3003

[api]
pathname = [
  "get | /basicInfo | postgres.getBasicInfo",
  "get | /tokenList | postgres.getAssetList",
  "get | /tokenInfo/:assetId | postgres.getTokenInfo",
  "get | /latestReceipts/:number | postgres.getLatestReceipts",
  "get | /lTxDetail/:hash | postgres.getLTxDetail",
  "post | /addressLTxList | postgres.getAddressLTxList",
  "get | /addressBalance/:address | postgres.getAddressBalance",
  "get | /stageInfo/:stageHeight | stage.getStageInfo",
  "get | /stageList/:amount | stage.getStageList",
  "post | /stageLTxList | stage.getStageLTxList"
]